### ISSUE TITLE
Should the demo plugin be separated from the main framework?

### ISSUE THREAD

**Issue by michaeluno** [michaeluno/admin-page-framework#138]
I'm wondering whether the demo plugin should be a separate plugin then make the main framework plugin just serve as a framework installer which just includes the framework file(s).  

This way, each developer who uses the framework does not have to call `include( 'admin-page-framework.min.php' )`. However, their plugin or theme will need to require the framework installer to be installed as a dependency so their products will not be portable. 

But I sense that some don't mind it and rather prefer that way. I'm not completely sure why but maybe it can avoid library conflicts or something.

**Comment by vladkucherov** [comment]
Hi guys,

Personally I would prefer a sepearate version of the framework from the demo. but if that's not an option and maybe some would prefer the demo in the package, maybe there should be a trigger to turn of the loading of the demo?

**FILE:** `admin-page-framework-demo.php`
```php
if(!defined('APFDEMO_LOAD') {
    define('APFDEMO_LOAD', true);
}

if(APFDEMO_LOAD) {
    /* Load examples */
    include( APFDEMO_DIRNAME . '/example/example-bootstrap.php' );
}
```

I think this may be the best solution for now until you'll decide what to do. personally I prefer the plugin as a plugin and not as a library inside my code.

Vlad.

**Comment by michaeluno** [comment]
@vladkucherov in v3.5.0 the demo part will be optional. 

You may try the 3.5.0b branch. https://github.com/michaeluno/admin-page-framework/tree/3.5.0b ([Download](https://github.com/michaeluno/admin-page-framework/archive/3.5.0b.zip))

> I prefer the plugin as a plugin and not as a library inside my code.

I'm curious whether you don't mind requiring your users to install an extra plugin for your products.

**Comment by vladkucherov** [comment]
@michaeluno No I don't mind because clients now understand that now 100% of the product they purchase is written by me. They know that if I would be required to recreate every single thing, the price would much more then it should be.

By having a plugin instead of a lib I get chance to receive updates from WP instead of updating things myself - and that's something priceless to me on the long term.

**Comment by michaeluno** [comment]
@vladkucherov Interesting point. Just be careful if anything breaks with the framework updates.

**Comment by vladkucherov** [comment]
@michaeluno Just because updating may become easier, doesn't remove the requirement for the developers to test everything after an update - this includes all the plugins, not just APF.

**Comment by michaeluno** [comment]
v3.5.0 has been released.
