### ISSUE TITLE
Sortable sections

### ISSUE THREAD

**Issue by dmgawel** [michaeluno/admin-page-framework#150]
Feature request:
Sortable sections, same as sortable fields (including tabbed sections).

**Comment by cmwwebfx** [comment]
Hi Michael, I would love to see this come to light also in one of the updates. A scenario of a use for this type of added feature is that we can create a group of fields in a repeatable section, then have these repeatable sections #176 be used for a simple slider type of metabox.

ie: (title, image upload, descriptions field). This is the base of being able to create a slider.

**Comment by michaeluno** [comment]
This is now available in a development branch. Download: [3.6.0b](https://github.com/michaeluno/admin-page-framework/archive/3.6.0b.zip)
