### ISSUE TITLE
Feature request - Add select 2 to select options

### ISSUE THREAD

**Issue by cmwwebfx** [michaeluno/admin-page-framework#152]
I love that this is a real contender for other admin frameworks out there, and would love to see that Select 2 is added into the framework.

http://ivaynberg.github.io/select2/

**Comment by michaeluno** [comment]
The `seelct2` field type has been added to the [dev](https://github.com/michaeluno/admin-page-framework/tree/dev) branch. Examples can be found via `Dashboard` -> `APF Demo` -> `Custom Field Types` -> `Select2`.
