### ISSUE TITLE
Repeated field elements will be changed not to dynamically update attributes

### ISSUE THREAD

**Issue by michaeluno** [michaeluno/admin-page-framework#158]
I've been wondering how an unlimited number of nested fields can be achieved and the biggest obstruction seems to be that the necessity of keeping the ability of repeating fields.

Currently when the `+` button is pressed, the framework updates the id and name attributes of the newly created element and the next siblings in JavaScript like this.

```
- Field 1
- Field 2 '+' is pressed
- Field 3
```

```
- Field 1
- Field 2 
- Field 2 copied and inserted
- Field 3
```

```
- Field 1
- Field 2 
- Field 3 the attributes are updated 
- Field 4 the attributes are updated 
```

In order to support nested fields, it seems to be almost impossible to update the attributes of each of nested items from the JavaSript side. So I'm going to change it by only giving the highest number of id and name to a newly copied item like the below.

```
- Field 1
- Field 2 '+' is pressed
- Field 3
```

```
- Field 1
- Field 2 
- Field 2 copied and inserted
- Field 3
```

```
- Field 1
- Field 2 
- Field 4 the attributes are updated 
- Field 3 
```

And when the form is submitted, the fields will be parsed on the PHP side and the id will be reassigned by the submitted order so the produced key structure will be the same as before.

Let me know if anybody will have a problem with this change.

**Comment by cmwwebfx** [comment]
Hi Michael, how are you going on this issue?

**Comment by michaeluno** [comment]
I haven't started this yet as this change requires a large block of time for me to concentrate which I have not been able to make. 

Before starting this one, a few bugs need to be fixed. Also, I'm preparing some acceptance and unit tests with CI, which is my current focus. If you want me to change the priorities, you may shoot me an email.
