### ISSUE TITLE
Sub-section (nesting collapsible sections)

### ISSUE THREAD

**Issue by cmwwebfx** [michaeluno/admin-page-framework#170]
Please could you look into the possibility to allow subsections or nested collapsible sections. If this were available I would write some CSS to be able to have left subsection and right subsection to allow a much tighter admin page. An example of this can be seen here in the screenshot below on how I would use it. 
Sub pages to open a full list of tabbed sections. Each tabbed section to have collapsible sub sections.

With screens getting bigger and bigger these days I can make use of some good CSS media queries to allow for these sub sections to sit side by side, and smaller screens to be stacked. This would produce a very smart looking options page utilising as much of the available screen size available.

With Admin Page Framework and the ability to be able to nest like that I believe I can reproduce the screenshot below quite easily.

![sub sections](https://cloud.githubusercontent.com/assets/1312880/5070841/ecca27e4-6eba-11e4-9b8d-0fc700987b82.png)

**Comment by michaeluno** [comment]
This is ready to be tested in the 3.7.0b branch. [Download](https://github.com/michaeluno/admin-page-framework/archive/dev.zip).

![nested_section_example01](https://cloud.githubusercontent.com/assets/3408158/11293320/793692b4-8f9c-11e5-96ee-130354cb1e4f.png)

## How to Use
Set nested section definitions in the `content` argument of the parent section.

```php
$oFactory->addSettingSections(    
    'my_page_slug', // the target page slug                
    array(
        'section_id'        => 'parent_section',
        'title'             => __( 'Nesting Sections', 'admin-page-framework-loader' ),
        'content'           => array(
            array(
                'section_id'    => 'nested_section_a',
                'title'         => __( 'Nested Section A', 'admin-page-framework-loader' ),                                                
            ),                                
            array(
                'section_id'    => 'nested_section_b',
                'title'         => __( 'Nested Section B', 'admin-page-framework-loader' ),
                'content'       => array(
                    array(
                        'section_id'    => 'nested_section_b_a',
                        'title'         => __( 'Nested Section B of A', 'admin-page-framework-loader' ),
                    ),                            
                    array(
                        'section_id'    => 'nested_section_b_b',
                        'title'         => __( 'Nested Section B of B', 'admin-page-framework-loader' ),
                    ),                                                    
                ),
            ),
            array(
                'section_id'    => 'nested_section_c',
                'title'         => __( 'Nested Section C', 'admin-page-framework-loader' ),
            ),                     
        ),
    )
);   
```

To add fields to nested sections, set an array of section path. If you want to add a field to a section whose ID is `nested_section_a`  that belongs to `parent_section`, set an array like `array( 'parent_section', 'nested_section_a' )` to the `section_id` argument of the field definition array.

```php
$oFactory->addSettingFields(
    array( 'parent_section', 'nested_section_a', ), // the target section ID - pass dimensional keys of the section
    array(
        'field_id'      => 'text_in_nested_section',
        'title'         => __( 'Text', 'admin-page-framework-loader' ),
        'description'   => __( 'Added to a nested section.', 'admin-page-framework-loader' ),
        'type'          => 'text',
        'repeatable'    => true,
        'sortable'      => true,
    ),
    array(
        'field_id'      => 'color_in_nested_section',
        'title'         => __( 'Color', 'admin-page-framework-loader' ),
        'type'          => 'color',
        'repeatable'    => true,
        'sortable'      => true,
    )
);
```

The example can be accessed via Dashboard -> Demo -> Advanced Usage -> Nesting. The code can be found in `/example/admin_page/nesting`. 

Let me know if it works.

@cmwwebfx I'm not sure if you are still interested in this but feedback would be appreciated.

**Comment by cmwwebfx** [comment]
This is fantastic Michael. I didn't get notified of this update from 14 days ago. I only saw it being closed off. Apologies not for responding sooner on this. I can test this next week.

I see what you have done instead of nesting collapsible sections is make nested tabbed sections. Is it possible to nest collapsible sections of options rather than nested tabbed options?

**Comment by michaeluno** [comment]
@cmwwebfx In this [example](https://github.com/michaeluno/admin-page-framework/blob/3.7.0/example/admin_page/advanced_usage/nesting/APF_Demo_AdvancedUsage_Nesting_SectionA.php), collapsible sections are nested under tabbed sections. So it is possible. The live example can be accessed via `Dashboard` -> `APF Demo` -> `Advanced Usage` -> `Nesting`. I'm not sure if you are referring to something different.

**Comment by cmwwebfx** [comment]
Ahh I see it now. The image was not clear that each tab has collapsible sections in each one.
