### ISSUE TITLE
Raw HTML field

### ISSUE THREAD

**Issue by ghost** [michaeluno/admin-page-framework#171]
Hi Michael,

Is it at all possible to have a raw HTML field so that it has no input other than being used for lets say an image or extra description to the bottom of each section? I looked through the documentation and tutorials to see if there was something like this already, but didn't see anything that eluded to this possibility.

**Comment by michaeluno** [comment]
Also as of v3.6.1, the `content` argument for the section and field definition is available. 

```
array(
...
    'content' => '<p>Your custom contents can be put here.</p>',
...
)
```
