### ISSUE TITLE
Sortable repeatable collapsible sections

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#183]
Hi guys,

I want tried to add `sortable` to `addSettingSection` when I created a `repeatable` & `collapsible` section, but looks like there was no reaction. I can't tell if it's a bug or just a lake of a feature because I haven't studied your framework to that point.

```php
$this->addSettingSection(
    array(
        'title'             => __('Columns'),
        'sortable'          => true,
        'repeatable'        => true,
        'collapsible'       => array(
            'toggle_all_button' => array( 'bottom-right' ),
            'container'         => 'section',
        ),
        'section_id'        => 'columns',
        'tab_slug'          => 'columns',
    )
);
```

Please help add / fix this issue :-)

Thanks :+1:

**Comment by michaeluno** [comment]
Hi, 

Sortable sections are not supported yet. https://github.com/michaeluno/admin-page-framework/issues/150

**Comment by vladkucherov** [comment]
Is there any chance to get it soon.

**Comment by michaeluno** [comment]
@vladkucherov I don't know. I'm working on v3.5.0 now and its loader plugin needs to be finished. After that what I'm planning to do is to change the mechanism of repeatable & sortable fields to support nested fields. But if you need sortable sections really soon, I can change the priority. In that case, email me. We can talk.

**Comment by vladkucherov** [comment]
@michaeluno No, that won't be necessary.

So 3.5.0 isn't ready yet? I thought you have finished the version.

**Comment by michaeluno** [comment]
@vladkucherov Regarding v3.5.0, the framework is ready but the loader plugin (which loads the framework) is not.
