### ISSUE TITLE
type='submit', 'reset' => 

### ISSUE THREAD

**Issue by soderlind** [michaeluno/admin-page-framework#185]
Two wishes

1.   `'reset' => true` and `'reset' => '"section_id"'` is working fine, but I'd like to do `'reset' => '"section_id"_"field_id"'` (i.e. reset just a field)
2.    I'd like to display different messages than "Please confirm your action" and "* Are you sure you want to reset the options?"

**Comment by michaeluno** [comment]
Good idea about the first issue. I barely remember it could be possible without modifications. Can you post a very simple small sample plugin just only shows that it does not work? Something like [this one](https://gist.github.com/michaeluno/d0eca4c0c02af911aabd) would work. 

The second issue can be solved by modifying the property of the `$oMsg` object.  I can show you how if there is a sample plugin.
