### ISSUE TITLE
3rd party tools missing in the repo?

### ISSUE THREAD

**Issue by cmwwebfx** [michaeluno/admin-page-framework#186]
Hi Michael,

I went to update today and noticed the 3rd party fields are not in the download or enqueued any more. Can you please advise what has happened to them?

Ciaran

**Comment by michaeluno** [comment]
Hi Ciaran, 

I think you mean the files of custom field types which were in the `third-party` directory. Most of them were removed and are now available as the [Field Type Pack](http://en.michaeluno.jp/admin-page-framework/field-type-pack/) add-on. A few of them have been moved to the `example/library/` directory. You can still use the files included in the previous version though.

**Comment by cmwwebfx** [comment]
Thank you for the clarification Michael. So the framework addons are now a commercial product? How does this affect the custom fields we already have in the previous version that we are building into a theme?

**Comment by michaeluno** [comment]
If you included the files in your distribution package, you are fine and your theme should not be affected by anything. Are you having an issue with this change?

**Comment by cmwwebfx** [comment]
No issue at all mate, am happy you made the decision to recoup the money based on development. My only thoughts are does this mean it will cost me $300 for future development on my themes or plugins, and is that unlimited themes and plugins? Will this cover future additions to the field type package?

I would be more than happy to pay this if that is so.

**Comment by michaeluno** [comment]
That's right except that you can receive updates up to 1 year from the date of purchase even with the unlimited license type. So if I add a new field type to the add-on after your license is expired, you won't have access to it unless you renew the license. Though this does not mean that your products become unable to operate after the license expiration unless a version incompatibility arises.

**Comment by cmwwebfx** [comment]
That is kind of what my worry is that version incompatibility arrises due to the framework no longer supporting older versions of the addons. However, I have plenty faith in what you develop anyway.

**Comment by michaeluno** [comment]
Thank you. That's nice of you to say. If you don't use the framework loader plugin but the renamed version of the minified version, you don't have to worry about version incompatibility though.
