### ISSUE TITLE
Tutorial Request - activation hook (about page)

### ISSUE THREAD

**Issue by cmwwebfx** [michaeluno/admin-page-framework#187]
Hi Michael,

I would like to request a few tutorials if that is fine to post here in Guthub?

First tutorial off the rank is the after plugin activation hook you have on the latest Admin Page Framework Plugin. I would love to know how you achieved that in a tutorial.

**Comment by michaeluno** [comment]
Hi Ciaran,

> I would like to request a few tutorials if that is fine to post here in Guthub?

Yes, fine.

> First tutorial off the rank is the after plugin activation hook you have on the latest Admin Page Framework Plugin. I would love to know how you achieved that in a tutorial.

Do you mean you'd like to see a tutorial that shows how to load your own plugin after the framework loader plugin is loaded?

**Comment by cmwwebfx** [comment]
Sort of. 
When I download and install / activate the APF plugin, the admin area is instantly redirected through like an after activation hook to the admin page framework about.php page with some tabs.

**Comment by michaeluno** [comment]
Ah, do you mean how to redirect the user to a certain page after plugin activation?

**Comment by cmwwebfx** [comment]
Yes correct, sorry for the long winded description. I have no idea what this is technically called, but it is exactly what I will like to do with a plugin that I am building using APF. A small tutorial on this I am sure will be well received by many that are in the same boat.

**Comment by michaeluno** [comment]
I see. Actually it does not use the framework code. Though I'll find some time to write a tutorial about it.

**Comment by cmwwebfx** [comment]
Fantastic Michael, I would appreciate that very much. In the mean time, could you please amend this page so it reflects the extension package with a link to the package.

http://en.michaeluno.jp/admin-page-framework/

That way you won't have people visiting that page and complaining they do not have these extended fields in the download.

**Comment by michaeluno** [comment]
Oh, I forgot about that. I will. Thanks for the heads-up!

**Comment by michaeluno** [comment]
Closing topic, I appreciate your feedback!
