### ISSUE TITLE
Warning after update to 3.5.0

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#189]
Hi,

on the pages that uses APF I get this warining:

> Strict Standards: Declaration of AdminPageFramework_FieldType::_replyToDoOnFieldRegistration() should be compatible with AdminPageFramework_FieldType_Base::_replyToDoOnFieldRegistration(array $aField) in /home/***/plugins/admin-page-framework/development/factory/AdminPageFramework_Factory/view/AdminPageFramework_FieldType/AdminPageFramework_FieldType.php on line 22

**Comment by michaeluno** [comment]
Oh, I guess type hinting is missing in the method of the `AdminPageFramework_FieldType` class. I'll check. If you can fix it by yourself and send a PR, would be appreciated.

**Comment by michaeluno** [comment]
v3.5.1.1 has been released which fixes this issue.
