### ISSUE TITLE
Warning after purchasing Field Types Pack Second issue

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#192]
Hi,

Another issue found:
> Strict Standards: Declaration of AdminPageFrameworkFieldTypePack_Setting_License::replyToDoTab() should be compatible with AdminPageFrameworkFieldTypePack_InPageTab::replyToDoTab() in /home/***/wp-content/plugins/admin-page-framework-field-type-pack/include/class/admin/setting/AdminPageFrameworkFieldTypePack_Setting_License.php on line 17

This could fixed multiple ways, so I leave you to decide.

**Comment by michaeluno** [comment]
Thanks for the report! I'll check.

**Comment by michaeluno** [comment]
Field Type Pack v1.0.1 has been released which should filed that problem.
