### ISSUE TITLE
Admin Page Framework - Field Type Pack won't update

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#198]
Hi,

Today I saw that I need to update this plugin, but after I returned to the page 5 min later, the update disappeared.

For now, I still use 1.0.0 and no update is required.

**Comment by michaeluno** [comment]
Hi,

An update of the loader plugin has been released today. So is there a chance that you thought it is the field type pack plugin? But if you are still using v1.0.0 and activated the license, you should get an update notice for the latest version 1.0.1.

**Comment by vladkucherov** [comment]
The license is active. Today I saw an update for the loader, and I updated sucessfully.
at first I saw 2 updated - for the loader and the plugin. but after I came back to update, the update of the plugin, disapeared. I still use 1.0.0. I verified at your website that you published 1.0.1, But I can't see it yet.

**Comment by michaeluno** [comment]
That's strange. Have you changed the directory name and the name of the plugin file of the field type pack plugin?

The directory name should be `admin-page-framework-field-type-pack` and the file name should be `admin-page-framework-field-type-pack.php`. If these are different, it may cause some unexpected behavior in the update notices.

**Comment by vladkucherov** [comment]
No. everything is correct. I haven't change a thing in the code (except previous warnings I reported about).

**Comment by michaeluno** [comment]
Do you have an object caching plugin activated? The updater of the field type pack uses `set_transient()` and I've seen some site enabling object caching having issues with that function.

**Comment by vladkucherov** [comment]
Nope. I use the default `wp_cache` function for now, this will be changed untill development is finished, but for now, no object caching here :smiley:

**Comment by michaeluno** [comment]
I'm not sure why then. Would be appreciated if you could do a little test.

1. Deactivate the license on the main site.
2. Have a clean installed WordPress site and only install the field type pack plugin.
3. Activate the license in that site.
4. Make sure the field type pack version is less than 1.0.1.
5. Wait if you get an update for at least an hour.

**Comment by michaeluno** [comment]
@vladkucherov So did you have a chance to try it on a test site? I'm wondering if you are using Windows for your development environment. I just came across an issue of plugin automatic updates with a Windows server and am going to release an update that includes a workaround for it.

**Comment by vladkucherov** [comment]
@michaeluno No I didn't have a chance to test it yet. this project has a very strict deadline :disappointed: I am working with Linux Ubuntu 14.04 x64 nginx. hope that helps

**Comment by vladkucherov** [comment]
@michaeluno Tested and it works like a charm :+1:

**Comment by michaeluno** [comment]
Glad to hear it!
