### ISSUE TITLE
Use advanced TinyMCE editor with Site Origin

### ISSUE THREAD

**Issue by vladkucherov** [michaeluno/admin-page-framework#201]
Good day,

I was wondering, how I can use more advanced editor?
![image](https://cloud.githubusercontent.com/assets/4151984/6325136/2bc619f2-bb4c-11e4-8ed6-77cd5219e903.png)

I would prefer it to be:
![image](https://cloud.githubusercontent.com/assets/4151984/6325142/3ec3f682-bb4c-11e4-9b0b-9087ee911784.png)

I couldn't find an option to set it "tiny". I did find this in your code:

```php
wp_editor(
    $aField['value'],
    $aField['attributes']['id'],
    $this->uniteArrays(
        (array) $aField['rich'],
        array(
            'wpautop' => true, // use wpautop?
            'media_buttons' => true, // show insert/upload button(s)
            'textarea_name' => $aField['attributes']['name'],
            'textarea_rows' => $aField['attributes']['rows'],
            'tabindex' => '',
            'tabfocus_elements' => ':prev,:next', // the previous and next element ID to move the focus to when pressing the Tab key in TinyMCE
            'editor_css' => '', // intended for extra styles for both visual and Text editors buttons, needs to include the <style> tags, can use "scoped".
            'editor_class' => $aField['attributes']['class'], // add extra class(es) to the editor textarea
            'teeny' => false, // output the minimal editor config used in Press This
            'dfw' => false, // replace the default fullscreen with DFW (needs specific DOM elements and css)
            'tinymce' => true, // load TinyMCE, can be used to pass settings directly to TinyMCE using an array()
            'quicktags' => true // load Quicktags, can be used to pass settings directly to Quicktags using an array()     
        )
    )
);
```
`AdminPageFramework_FileType_textarea.php` ***Line:*** *517*

I did find that you set ``tiny => false`` but I still get the *tiny* one.

Any ideas?

**Comment by michaeluno** [comment]
Maybe
```php
    'teeny' => false,
```

not
```php
    'tiny' => false,
```

It should be already `false` by default though.

**Comment by vladkucherov** [comment]
in `wp-includes/class-wp-editor.php` ***Line:*** *318* it's `teeny` so your code key is correct but still doesn't explain why I get the `teeny` one :disappointed:

**Comment by michaeluno** [comment]
How do you set the `rich` argument?

It should look like

```php
    'rich' => array(
         'teeny' => false,
    ),
```

You may post a very simple example plugin that only demonstrates the problem so that others can reproduce the problem, something like [this one](https://gist.github.com/michaeluno/d0eca4c0c02af911aabd).

**Comment by vladkucherov** [comment]
the default is `teeny => false`, and it looks like you don't change it.
of course I don't change it - so it leaves us with an issue not with the settings

**Comment by vladkucherov** [comment]
I came up with this idea...
The post edit page already loads the WYSIWYG editor, but then SiteOrigin Panels (after it loads) hides the editor.
After, when you try to open the widget that has WYSIWYG it won't show it as rich editor because the rich one is already has been loaded.

The idea is based on what i saw in `wp_editor` any ideas?

**Comment by vladkucherov** [comment]
Did you have a chance to take a look at this?

**Comment by vladkucherov** [comment]
Like you requested I created a gist of a widget using the editor
https://gist.github.com/vladkucherov/9c881d14b8b2d75da9de

**Comment by michaeluno** [comment]
I could reproduce the problem in my environment. 

To see what is going on, I changed the constructor of your code to check the passed TinyMCE settings.

```php
	public function __construct() {
		parent::__construct('Text Section', array(
			'classname'     => 'widget_text_section',
			'description'   =>  'Some description'
		));
               
        add_filter( 'tiny_mce_before_init', array( $this, 'replyToLogTinyMCESettings' ) );

	}

        public function replyToLogTinyMCESettings( $aTinyMCESettings ) {
            
            AdminPageFramework_Debug::log( $aTinyMCESettings );
            return $aTinyMCESettings;
            
        }
```
The log indicates that the textarea id is modified by the SiteOrigin plugin. You'll see something like this.

```
    [selector] => #widget-text_section_widget-{$id}-tf_content__0
```
The part `{$id}` is where being modified. This means the set options in the `rich` field argument of APF will not be set because they change the textarea ID after the TinyMCE settings for the field are passed and apply their original ID afterwards.

Still, it should be possible to apply the default TinyMCE settings to an APF generated textarea field. You may try to find a hook which gets triggered when they apply an ID to the widget, the code that converts an ID like `widget-text_section_widget-{$id}-tf_content__0` to `widget-text_section_widget-c14-tf_content__0` Let me know if you find one.

**Comment by michaeluno** [comment]
Closing the topic due to inactivity.
