### ISSUE TITLE
Metabox not stored on intial save/publish

### ISSUE THREAD

**Issue by matt2314** [michaeluno/admin-page-framework#211]
I have added a single text-area to regular posts via AdminPageFramework_MetaBox. With version 3.5.7.1 of the plugin I now have the problem that the value is not stored when I hit save or publish for the first time. On subsequent updates everything works as expected though.

Tested on:
- WordPress 4.1.1 multisite, Admin Page Framework 3.5.7.1
- WordPress 4.2.2 multisite, Admin Page Framework 3.5.7.1

Issue did not happen in those same setups with Admin Page Framework 3.5.6.

See thread on wordpress.org: https://wordpress.org/support/topic/metabox-not-stored-on-intial-savepublish

**Comment by michaeluno** [comment]
Thanks for the report.

I've uploaded a development branch [3.5.8b](https://github.com/michaeluno/admin-page-framework/archive/3.5.8b.zip) which includes this fix. 

Let me know if it works for you.
