### ISSUE TITLE
Acumulative slashes on wp_editor

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#214]
Hi,

have put a TinyMCE editor in a taxonomy, I realized that I always keep slapshes added to resave values.

[Youtube id = //// "9dbme8bmiBs ////"]

I've solved by changing the code in AdminPageFramework_FieldType_textarea.php to:

Line 447: wp_editor(stripslashes($aField['value']) , $aField['attributes']['id'], $this->uniteArrays(( array )$aField['rich'], array('wpautop' => true, 'media_buttons' => true, 'textarea_name' => $aField['attributes']['name'], 'textarea_rows' => $aField['attributes']['rows'], 'tabindex' => '', 'tabfocus_elements' => ':prev,:next', 'editor_css' => '', 'editor_class' => $aField['attributes']['class'], 'teeny' => false, 'dfw' => false, 'tinymce' => true, 'quicktags' => true)));
        

I hope if this is a favorable solution, the inclusion in the next version.

best regards

**Comment by michaeluno** [comment]
I could confirm the problem. Thanks for the report.

I've uploaded [3.5.10b](https://github.com/michaeluno/admin-page-framework/archive/3.5.10b.zip) so you may try that and let me know if that fixes the issue.

**Comment by xarkitu** [comment]
Hi,

The compiled version 3.5.10b. for my plugin and tested, it works correctly.

Michaeluno Many thanks.
