### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by mst404** [michaeluno/admin-page-framework#217]
Hi, If the possible, add framework to composer package.

Regards

**Comment by michaeluno** [comment]
Hi,

Can you explain how it will be useful?

**Comment by mst404** [comment]
I think it would be useful for developers and plugin authors.

**Comment by CAYdenberg** [comment]
+1.

Details:

A common use-case for this repo is development of other plugins (or themes) - therefore it is a dependency more than a plugin that needs to be exposed to the dashboard. Composer gives you the ability to include it in projects very easily, and keep it up to date.

Additionally, you get namespacing for free, so if multiple projects on the same WP installation use admin-page-framework, they won't conflict with each other. They can even each use their own different version!

**Comment by michaeluno** [comment]
I'll think about it.
