### ISSUE TITLE
Fatal error: Call to a member function getClassAttribute()

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#219]
Hi,

the framework gives me an error:

Fatal error: Call to a member function getClassAttribute() on a non-object in /framework/utility/AdminPageFramework_AdminNotice.php on line 6

The line 6 contains:

$this->aAttributes['class'] = $this->oUtil->getClassAttribute($this->oUtil->getElement($this->aAttributes, array('class'), ''), 'settings-notice-message', 'notice is-dismissible');

If I change this code by the old code:

$this->aAttributes['class'] .= ' admin-page-framework-settings-notice-message';

The class works normally.

I'm working with the compiled framework within my own plugin.

I hope to help serve and that the problem has a solution.

Best regards

**Comment by michaeluno** [comment]
Hi,

Thanks for the report. The code of that class has an obvious error .

By the way, just in case, does it only happen when you try to instantiate the `AdminPageFramework_AdminNotice` class? Or does it happen when you activate the framework loader or do something like opening a page or submitting a form?
