### ISSUE TITLE
The fields do not hide under the condition if, on AdminPageFramework_TaxonomyField

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#221]
Hi,

I'm trying to hide fields according to taxonomies call class, is that they do not obey when I put the "if"

'if' => $dontShow

In the other classes of the framework I'm using and I have no problem to hide fields according to condition.

This is a bug?

Thankful in advance for your treatment and your job

**Comment by michaeluno** [comment]
I could confirm the problem. It should be a bug. 

Thanks for the report.
