### ISSUE TITLE
Can't change metabox position.

### ISSUE THREAD

**Issue by ikixxx** [michaeluno/admin-page-framework#224]
Referring to the tutorial 9 [Add metabox in admin page](http://admin-page-framework.michaeluno.jp/tutorials/09-add-a-meta-box-in-an-admin-page/) I can't seem to move the metabox in to the **main** area.
It always appears on the side, `context` property doesn't change anything.
And if I introduce sections, then metabox is pushed down.
![screenshot_00220151117 t](https://cloud.githubusercontent.com/assets/390700/11223980/fd27e39c-8d72-11e5-80ce-bbdb15cc43e3.png)

**Comment by michaeluno** [comment]
That's strange. 

Can you check if you get the same problem in the loader plugin admin page accessed via Dashboard -> Admin Page Framework -> Help -> Report? That page has setting fields and also a page meta box.

**Comment by ikixxx** [comment]
Yes, metabnox is in top right.

**Comment by ikixxx** [comment]
Try this code:
I still can't make the metabox go to top right, maybe I'm doing somethign wrong, or it might be some kind of CSS issue.
```php
class iki_MainThemeOptions extends AdminPageFramework {

	public function setUp() {

		$this->setRootMenuPage(
			'Theme Options'
		);

		$this->addSubMenuItems(
			array(
				'title'     => 'Global Options',
				'page_slug' => 'iki_global_options',
			), array(
			'title'     => 'Second Global',
			'page_slug' => 'iki_other_options',
		) );

		$this->addSettingSections(
			'iki_global_options',
			array(
				'section_id'  => 'my_first_section',
				'title'       => 'My First Form Section',
				'description' => 'This section is for text fields.',
			),
			array(
				'section_id'  => 'my_second_section',
				'title'       => 'My Second Form Section',
				'description' => 'This section is for selectors.',
			)
		);
		$this->addSettingFields(
			'my_first_section',    // target page slug
			array(
				'field_id'   => 'my_color',
				'type'       => 'color',
				'title'      => 'Color',
				'repeatable' => true,
				'sortable'   => true,
			),
			array(
				'field_id'   => 'my_image',
				'type'       => 'image',
				'title'      => 'Image',
				'repeatable' => true,
				'sortable'   => true,
				'attributes' => array(
					'style' => 'max-width: 300px;',
				)
			)
		);
		$this->addSettingFields(
			'my_second_section',    // target page slug
			array(
				'field_id'   => 'my_color',
				'type'       => 'color',
				'title'      => 'Color',
				'repeatable' => true,
				'sortable'   => true,
			),
			array(
				'field_id'   => 'my_image',
				'type'       => 'image',
				'title'      => 'Image',
				'repeatable' => true,
				'sortable'   => true,
				'attributes' => array(
					'style' => 'max-width: 300px;',
				)
			)
		);
	}

}

new iki_MainThemeOptions();

```

and for metboxes
```php
class APF_Tutorial_SidePageMetaBox extends AdminPageFramework_MetaBox_Page {

}

new APF_Tutorial_SidePageMetaBox(
	null,                                           // meta box id - passing null will make it auto generate
	__( 'Side Page Meta Box', 'admin-page-framework-tutorial' ), // title
	'iki_global_options',
	'normal',                                         // context
	'default'                                       // priority
);
```

**Comment by michaeluno** [comment]
It seems the dev version has a problem. If you are using it, can you go back to the stable version and see if the problem goes away? 

To check the included library version, you can find it by moving your mouse over the footer link named Admin Page Framework in the created admin page.

**Comment by michaeluno** [comment]
I just noticed that you need to set `side` to the context parameter.

```php
new APF_Tutorial_SidePageMetaBox(
    null,                                           // meta box id - passing null will make it auto generate
    __( 'Side Page Meta Box', 'admin-page-framework-tutorial' ), // title
    'iki_global_options',
    'side',                                         // context <--- this one!
    'default'                                       // priority
);
```

Let me know if this fixes your problem.

By the way, the dev branch has been updated and it fixes an issue of adding form fields without in-page tabs. Also never mind what I said that a bug was introduced in v3.5.5. That wasn't the case. The dev branch had an issue of loading incorrect files.

**Comment by ikixxx** [comment]
I've tried with `side` , it's not in the code I posted previously, put I've tried all three valid options.

**Comment by michaeluno** [comment]
Okay, I could confirm this problem finally when no `side` meta box exists and a `normal` or` advanced` one gets added. I'll change the framework code to set `1` to the screen layout option when no side meta box exists.

Thanks for the report.

**Comment by michaeluno** [comment]
v3.6.5 has been released which includes this fix.
