### ISSUE TITLE
Grammar error and 502 Bad Gateway

### ISSUE THREAD

**Issue by ivandotv** [michaeluno/admin-page-framework#226]
![screenshot_00120151117 t](https://cloud.githubusercontent.com/assets/390700/11224893/878b6050-8d77-11e5-91ad-b13c4f072f5b.png)

Also, clicking on "Multiple Export Buttons" text gives "502 Bad Gateway"

**Comment by michaeluno** [comment]
The typo of the button label will be fixed, thank you.

Regarding the 502 Bad Gateway error, I cannot reproduce it on my end. Can you try a clean install to see if the problem still occurs? Install a new WordPress test site only with the default theme and the Admin Page Framework loader plugin. Let me know how it goes.

**Comment by ikixxx** [comment]
will do that , and report back. 
Btw, I'm using nginx.

**Comment by michaeluno** [comment]
Closing the topic as the problem cannot be confirmed.
