### ISSUE TITLE
There is an error in repeating fields

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#232]
There is an error in repeating fields, these are not properly displayed or stored.

I'm looking for the reason, if I find some reason'll let you know here.

![captura](https://cloud.githubusercontent.com/assets/5380013/12377518/0c695ed4-bd21-11e5-98bc-d17a8d33a145.JPG)

**Comment by michaeluno** [comment]
I neither see any problem from your picture nor confirm any problem in my environment. Can you mark the fields having an issue in the picture? 

Also post more details including the followings:
- whether a problem occurs with a particular field type.
- any error messages in the browser console. (in Chrome, right click -> Inspect Element -> Console)
- any PHP error logs
- WordPress version
- Admin Page Framework version

**Comment by xarkitu** [comment]
Hi michaels

Sorry for not giving more details, my environment is as follows:

WP = 4.4.1
APF =  3.7.11

The problem is these repeated fields
In my plugin I have the same behavior with a compilation generated useful compilation.
In principle teaches values, you change values and guards, then disappear.

![captura](https://cloud.githubusercontent.com/assets/5380013/12380996/e2c0a5be-bd80-11e5-9f22-6dda59623615.JPG)

I have no error displayed on the console of Chrome.
No error php on log.

Thank you for this great plugin and their hard work.

**Comment by xarkitu** [comment]
I confirm that the values are kept by APF, but are not shown later.


[sizes_field] => Array
                (
                    [0] => Array
                        (
                            [0] => Array
                                (
                                    [size] => 3415
                                    [unit] => g
                                )

                        )

                    [1] => Array
                        (
                            [0] => Array
                                (
                                    [size] => 13400
                                    [unit] => mm
                                )

                        )

                    [2] => Array
                        (
                            [0] => Array
                                (
                                    [size] => 343430
                                    [unit] => mb
                                )

                        )

                )

**Comment by michaeluno** [comment]
I could confirm the problem.

It seems to have started since v3.7.0. 

The saved options structure appears to be wrong it should be like

```
[sizes_field] => Array
                (
                        [0] => Array
                            (
                                [size] => 3415
                                [unit] => g
                            )

                    )
```

Probably the wrong `name` attribute value of the input is generated. I'll investigate it. 

Thanks for the report.

**Comment by michaeluno** [comment]
Should have been fixed in the [development branch](https://github.com/michaeluno/admin-page-framework/tree/dev). It would be appreciated if you could confirm it works.

**Comment by xarkitu** [comment]
Hi

I confirm that I now works well both as APF plugin and compiled within my plugin.

Thank you very much for your quick support, I am birseye endeavor to assist in any way possible.
