### ISSUE TITLE
archive is damaged or unknown format

### ISSUE THREAD

**Issue by m-kuznetsov** [michaeluno/admin-page-framework#234]
generation is successful, but the archive is damaged or unknown format?

**Comment by michaeluno** [comment]
Are you talking about the Generator (Dashboard -> Admin Page Framework -> Tools)? If so, the file you download should be a zip file.

**Comment by michaeluno** [comment]
I could confirm the problem. It may only occur on Windows. For a temporary workaround, use [7zip](http://www.7-zip.org/download.html). 

Duplicate: #235
