### ISSUE TITLE
Booleans are not printable

### ISSUE THREAD

**Issue by szepeviktor** [michaeluno/admin-page-framework#240]
Please fix boolean printing.
```php
$_sRpeatable = getAOrB( $bRpeatable, 'true', 'false' );
$_sExternalSource = getAOrB( $bExternalSource, 'true', 'false' );
```
https://github.com/michaeluno/admin-page-framework/blob/master/library/apf/factory/_common/form/field_type/AdminPageFramework_FieldType_media.php#L442

**Comment by szepeviktor** [comment]
Also here
https://github.com/michaeluno/admin-page-framework/blob/master/library/apf/factory/_common/form/field_type/AdminPageFramework_FieldType_media.php#L769

**Comment by michaeluno** [comment]
I'm trying to understand what the problem is but haven't gotten it yet. Can you add some more information for me so that I'll understand?

**Comment by szepeviktor** [comment]
The plugin tries to echo booleans into JavaScript which does not result in the string `true` or `false`.
```js
jQuery( document ).ready( function(){
    setusunlocked_AdminPageFrameworkImageUploader( '{$sInputID}', '{$bRpeatable}', '{$bExternalSource}' );
});
```

**Comment by szepeviktor** [comment]
PHP Notice:  Array to string conversion in /inc/apf/factory/_common/form/field_type/AdminPageFramework_FieldType_media.php on line 442

**Comment by michaeluno** [comment]
> The plugin tries to echo booleans into JavaScript which does not result in the string true or false

The value types in that functions you linked are loosely handled. However, I don't see any issue in the resulting behavior in the program.

Just for intelligibility of the code, I've changed the variable types passed to the `setAdminPageFrameworkImageUploader()` and `setAdminPageFrameworkMediaUploader()` functions. 

> PHP Notice: Array to string conversion in /inc/apf/factory/_common/form/field_type/AdminPageFramework_FieldType_media.php on line 442

Can you provide the steps to reproduce it?

**Comment by szepeviktor** [comment]
`Rpeatable` could be an array:
```php
                'repeatable'    => array(
                    'max' => 4,
                ),
```

**Comment by michaeluno** [comment]
I see. I could confirm that PHP notice. Thanks for the report.

**Comment by szepeviktor** [comment]
Thanks.

**Comment by michaeluno** [comment]
You are welcome!
