### ISSUE TITLE
Create metaboxes for a specific page template

### ISSUE THREAD

**Issue by szepeviktor** [michaeluno/admin-page-framework#245]
> The post type(s) or screen ID that the meta box is associated with.

Could I tie metaboxes to - let's say - the front page only?

**Comment by michaeluno** [comment]
Do you mean you want to display meta boxes in the front-end?

**Comment by szepeviktor** [comment]
NO!!!
On the back-end. But only for a certain page template.

**Comment by michaeluno** [comment]
Do you mean this?

![page_template](https://cloud.githubusercontent.com/assets/3408158/13193041/fac3ec44-d7b5-11e5-8717-54d364d818d3.png)

When the user select an item in the select drop-down, do you want to display an associated meta box?

**Comment by szepeviktor** [comment]
> When the user selects an item in the Template select drop-down , do you want to display an associated meta box?

Actually when the template is already set, thus after hitting Publish/Update.

**Comment by michaeluno** [comment]
You can set an empty array to the `$this->oProp->aPostTypes` property to disable the post meta box in the `setUp()` method.

```php
    public function setUp() {
    
        ...
        
        if ( ...not the desired template... ) {
            $this->oProp->aPostTypes = array();
        }
        
        ...
        
    }
```

**Comment by szepeviktor** [comment]
Thank you!
