### ISSUE TITLE
Image type field

### ISSUE THREAD

**Issue by szepeviktor** [michaeluno/admin-page-framework#246]
If I set the image field repeatable the first modal is titled "Insert Media"
the second one "Upload Image" thus has no "Insert from URL" tab.

**Comment by michaeluno** [comment]
I could not confirm the problem. At least in the demo, it looks working fine. Tell me if not. 

Maybe you want to try the `allow_external_source` argument which accepts a boolean value of `true` or `false`.

**Comment by szepeviktor** [comment]
This is the result of my *fix* of the JavaScript in #240.
Excuse me.
