### ISSUE TITLE
Term meta

### ISSUE THREAD

**Issue by szepeviktor** [michaeluno/admin-page-framework#247]
Do you plan to support term meta?

For others: Now term meta is stored in wp_options.

**Comment by michaeluno** [comment]
If you are talking about the one introduced in WordPress v4.4, I don't mind. In that case, a new factory class needs to be introduced.

**Comment by michaeluno** [comment]
I've uploaded a [new branch](https://github.com/michaeluno/admin-page-framework/tree/3.8.0/term_meta_factory) which includes this feature.

An example is located in [`/example/term_meta`] (https://github.com/michaeluno/admin-page-framework/blob/3.8.0/term_meta_factory/example/term_meta/APF_TermMeta.php). 

This lets you retrieve term meta data with `get_term_meta()`.

```
    $value = get_term_meta( $iTermID, 'my_filed_id', true );
```

**Comment by szepeviktor** [comment]
Thank you.
