### ISSUE TITLE
How to use Namespace Classes in hooks with {instantiated class name}

### ISSUE THREAD

**Issue by webstractions** [michaeluno/admin-page-framework#249]
I am trying to wrap my head around using Namespaced classes in callback hook functions that use _{instantiated class name}_ as part of the function name.

Namespaced classes use '/' and not underscores. I am having a problem figuring out how to add actions and filters.

**Comment by michaeluno** [comment]
Hi,

I've uploaded an example [here](https://gist.github.com/michaeluno/45c900ee56d3063776b4). You can simply download and install it as a plugin. 

Hope it helps.

**Comment by webstractions** [comment]
Thanks Michael. Helped immensely. I was trying to use the class name as part of the method name within the class to avoid having to add the action or filter. Guess that is not possible, but no worries. Thought I was missing something in my train of thought. Thanks again.

**Comment by michaeluno** [comment]
I see. For the dynamically generated functions for hooks, you need to replace `\` with `_`. If your class name is like `Foo\Bar\MyClass` then the function name used in the class should be `Foo_Bar_MyClass`.
