### ISSUE TITLE
AdminPageFramework_TaxonomyField class does not work properly in WP 4.5.0

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#251]
Hi,
Here I am again with another bug.

After updating my sites to WP 4.5.0, the AdminPageFramework_TaxonomyField class has stopped working properly.

I have put into categories custom fields by creating a new category if I teach them to fill. but once I try categoías edit fields are not shown.

You could check this ?, if you need any more information let me know.

Best regards
Javier

**Comment by xarkitu** [comment]
I confirmed that the use of APF standard version as part of plugin use the same fault occurs

![captura-apf-edit](https://cloud.githubusercontent.com/assets/5380013/14498286/25ee3254-019a-11e6-8f57-c1a3ec94d2e6.JPG)
![captura-apf-new](https://cloud.githubusercontent.com/assets/5380013/14498287/25f04ef4-019a-11e6-805c-5631928574b6.JPG)

**Comment by michaeluno** [comment]
Hi,

I could confirm the problem. It must be due to the change in the WordPress core of v4.5 described [here](https://make.wordpress.org/core/2016/03/07/changes-to-the-term-edit-page-in-wordpress-4-5/). 

I'll see how this could be fixed. Thanks for the report!

**Comment by michaeluno** [comment]
@xarkitu I've uploaded a [branch](https://github.com/michaeluno/admin-page-framework/tree/3.7.14b) with a fix so please try it and see if it works.

**Comment by xarkitu** [comment]
Hi Michaeluno,

I checked in plugin mode and within my plugin compiled and seems to be working well.

Thank you very much for the support.

**Comment by michaeluno** [comment]
v3.7.14 has been released.
