### ISSUE TITLE
Description not uodated for new path custom field type.

### ISSUE THREAD

**Issue by BHWD** [michaeluno/admin-page-framework#261]
As you will see the description for the path type is the same as the github button. 

<img width="682" alt="screen shot 2016-09-24 at 21 24 37" src="https://cloud.githubusercontent.com/assets/5808219/18811032/6b18266c-829d-11e6-9fb7-1f6956f1c3ac.png">

**Comment by michaeluno** [comment]
v3.8.5 has been released.
