### ISSUE TITLE
Dependency action

### ISSUE THREAD

**Issue by Lder** [michaeluno/admin-page-framework#262]
Hello,
Is there any option where I can create dependency action.
For example, show a color when the user check a checkbox.

Thanks.

**Comment by michaeluno** [comment]
To just show/hide particular elements, you can do that with the `revealer` field type included in the [Field Type Pack](http://admin-page-framework.michaeluno.jp/add-ons/field-type-pack/).

What other actions are you expecting to have?

**Comment by Lder** [comment]
Hello
Thanks for the answer.

What I want to do this:
I have a set of radio buttons, when the user chooses option 1, it reveals a color, if it chooses option 2 it reveals a color and 1 input text.

The idea is to show options according to the chosen fields.

**Comment by michaeluno** [comment]
The `revealer` field type mentioned above can handle it.
