### ISSUE TITLE
Bug | Image upload on Widgets

### ISSUE THREAD

**Issue by heldervilela** [michaeluno/admin-page-framework#263]
Hello,
I want to report 2 bugs.

They are both related to widgets on customizer.

- ( [video](https://www.dropbox.com/s/j7ztwz0pf0my63u/bug-1.mov?dl=0) ) When adding a new widget the image upload does not work. 
- ( [video](https://www.dropbox.com/s/xo91gjant4majz0/bug-2.mov?dl=0) ) When editing a widget the image upload does not refresh the page to update the content. 

Thanks for the fantastic framework.

**Comment by michaeluno** [comment]
Hi,

So you are talking about Customizer. I could confirm the problem. Thanks for the report.

I remembered it was working a while back so just tried it with different WordPress versions. And It seems the problem occurs in WordPress 4.6, 4.5, and 4.4 and does not occur in WordPress 4.3.

Since you say widgets, can you check whether it occurs in widgets.php (Dashboard -> Appearance -> Widgets)?

**Comment by Lder** [comment]
Hello
This just happens in the customizer, on the widgets.php page works fine.
Can you give me some direction to try fix it?

**Comment by michaeluno** [comment]
For widgets to support the Selective Refresh mechanism of Customizer, its handling logic must be introduced.

- https://developer.wordpress.org/themes/advanced-topics/customizer-api/#widget-support
- https://make.wordpress.org/core/2016/03/22/implementing-selective-refresh-support-for-widgets/

Admin Page Framework lets each field type define what scripts and styles to load. The `image` field type in particular defines its script in the `getScripts()` method.

- https://github.com/michaeluno/admin-page-framework/blob/3.8.10/development/factory/_common/form/field_type/AdminPageFramework_FieldType_image.php#L98

Also, although this is rather a user-side approach, when you instantiate an APF widget class, you may want to set the `customize_selective_refresh` argument.


```php
new APF_Widget_Example( 
    'Widget Title',  // widget tite
    array(
        'description' => 'This is a widget description.',    // description
        'customize_selective_refresh' => true, // <--- this one
    ),
);
```

**Comment by Lder** [comment]
Thank you.
I'll give it a try.
