### ISSUE TITLE
Field Arguments

### ISSUE THREAD

**Issue by mnajafzadeh** [michaeluno/admin-page-framework#265]
Hi,

Is there any solution to turn-off the "Field Arguments" without turning of the WP_DEBUG constant?

> Admin Page Framework 3.8.12 (This information will be disabled when WP_DEBUG is set to false in wp-config.php.)

Thank you.

**Comment by mnajafzadeh** [comment]
Found the solution:

'show_debug_info'   => false

**Comment by mnajafzadeh** [comment]
Sorry,

I couldn't find anything on documentation!
I still get "Debug Info: Admin Page Framework 3.8.12" on MetaBox pages. Is there any solution like:

`        $this->addSubMenuItems(
            array(
                'title' => __( 'Settings', 'social-board-admin' ),
                'page_slug' => 'my_settings',
                **'show_debug_info' => false**
            ),`

But, for MetaBoxes?

![github-wp_debug](https://cloud.githubusercontent.com/assets/5845453/21285792/cbe35722-c457-11e6-8e5f-414d487f5d49.png)

Thank you.

**Comment by michaeluno** [comment]
You can directory modify the property value. Add this in the `setUp()` method.

```php
    $this->oProp->bShowDebugInfo = false;
```

**Comment by mnajafzadeh** [comment]
Hi,

I did this before I mention here but, it didn't work!

**Comment by mnajafzadeh** [comment]
Sorry,
I was adding this into a wrong file. It is OK now.

Thank you too much.
