### ISSUE TITLE
Widget UI Improvement: add tabbed groups

### ISSUE THREAD

**Issue by pagelab** [michaeluno/admin-page-framework#267]
Hi,

I have a suggestion: right now, when a widget have lots of fields, it can easily extend the height of the window in small screens, which is far from optimal.

It would be more efficient if we could group fields into tabs in order to save space and increase usability. An example:

![tabbed-widget-fields-1](https://cloud.githubusercontent.com/assets/1451087/25569361/5abbda2a-2dec-11e7-9b6a-0ef2e771f858.gif)

[Here's a test widget](https://github.com/michaeluno/admin-page-framework/files/967123/widget_test.zip) (not created with APF) if you want to play with the concept.

**Comment by michaeluno** [comment]
Hi,

You should try section tabs.

**Comment by pagelab** [comment]
Thanks for the clue!
