### ISSUE TITLE
[x] Namespace bug

### ISSUE THREAD

**Issue by dualjack** [michaeluno/admin-page-framework#270]
I have found a bug, when creating root menu page while using namespacing.
When namespace occurs, some things are broken.

The simplest code to reproduce it:

```
<?php
namespace tmc\newsletter\src\Controllers;


class apf_mainPluginPages extends \ns_tmcAdminPageFramework {

    function setUp() {
        
        $this->setRootMenuPage( 'I am broken' );

        $this->addSubMenuItems(
            array(
                'title'         =>  __( 'Emails', 'ns_tmc' ),
                'page_slug'     =>  'ns_tm_emails'
            )

        );

    }

}

new apf_mainPluginPages( 'ns_tmc_options', $this->mainPluginFile, 'manage_options', 'ns_tmc'  );
```

![screenshot_1](https://user-images.githubusercontent.com/8117031/27001974-bbca7af6-4dd6-11e7-9c46-1db35da661af.png)

As you can see, it creates root menu but also sub menu with broken link.
The broken link follows namespace structure.

When namespaceing is gone, everything works fine.

```
<?php
class apf_mainPluginPages extends ns_tmcAdminPageFramework {

    function setUp() {

        $this->setRootMenuPage( 'I am broken' );

        $this->addSubMenuItems(
            array(
                'title'         =>  __( 'Emails', 'ns_tmc' ),
                'page_slug'     =>  'ns_tm_emails'
            )

        );

    }

}

new apf_mainPluginPages( 'ns_tmc_options', $this->mainPluginFile, 'manage_options', 'ns_tmc'  );
```

![screenshot_2](https://user-images.githubusercontent.com/8117031/27002059-f91f7770-4dd7-11e7-95cd-feefcff131d2.png)

I am not sure for now, but maybe transforming className, used in scripts, to some safe string without backslashes will fix it.

I think this problem occurs, because wordpress method add_menu_page() returns slug with "/" not "\\".

**Comment by dualjack** [comment]
Don't mind `$this->mainPluginFile`
I just moved it from upper file for simplicity.

**Comment by michaeluno** [comment]
I could confirm this problem. Thanks for the report.
