### ISSUE TITLE
Sortable checkbox problem

### ISSUE THREAD

**Issue by mnajafzadeh** [michaeluno/admin-page-framework#271]
## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [x] The issue still exists against the latest `dev` branch.
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1. Install the plugin downloaded form https://wordpress.org/plugins/admin-page-framework/
2. Enable the Demo
3. In WP Dashboard, go to APF Demo > Built-in Field Types
4. Go to Selectors tab
5. Under Check-boxes section the Sortable is not working as expected. Following I explained how to find this,

## Expected behavior and actual behavior

I changed the code as follow to have one of the columns like q, r, s
```
            array( // sortable check boxes
                'field_id'      => 'checkbox_sortable_fields',
                'title'         => __( 'Sortable', 'admin-page-framework-loader' ),
                'type'          => 'checkbox',
                'label'         => array( 'x', 'y', 'z' ),
                'sortable'      => true,
                array(
                	'label'         => array( 'q', 'r', 's' ),
                ), // the second item
                array(), // the third item
                array(), // the fourth item
            )
```
Them I dragged the q, e, s row to the end and clicked Save.
I was expecting to have the row at the end but, it stays at the same place and only the checked items are moved to the last.

### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

### Versions

- Admin Page Framework version: 3.8.15
- WordPress version: 4.5.9
- PHP version: 5.6.0

## Isolating the problem

- [x] This bug happens on the demo page.
- [x] The bug happens consistently across all tested browsers.
- [x] This bug happens with clean install (with the default theme and no plugin except the problematic one).

**Comment by michaeluno** [comment]
> I was expecting to have the row at the end but, it stays at the same place and only the checked items are moved to the last.

That's how it is supposed to be. It's not a bug. You are just changing the labels of the second row, which is applied every time the rows are applied. 

If you need to let the user sort set of check boxes with different labels, you want to try nested fields or inline fields.

**Comment by mnajafzadeh** [comment]
Hi,

I want to let user to sort a set of checkbox elements. Could you please, show me an example?

Thank you.
