### ISSUE TITLE
Widgets error on WP v4.8.1

### ISSUE THREAD

**Issue by mnajafzadeh** [michaeluno/admin-page-framework#273]
## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [x] The issue still exists against the latest `dev` branch.
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

After updating to WP v4.8.1, lots of themes have conflict problem with Admin Page Framework. An example error I get on the website when Admin Page Framework is initiated:
WARNING: ARRAY_MERGE(): ARGUMENT #2 IS NOT AN ARRAY IN (…)/WP-INCLUDES/DEFAULT-WIDGETS.PHP ON LINE 117

### Versions

- Admin Page Framework version: 3.8.15
- WordPress version: 4.8.1
- PHP version: 5.6

## Isolating the problem

- [x] This bug happens on the demo page.
- [x] The bug happens consistently across all tested browsers.
- [x] This bug happens with clean install (with the default theme and no plugin except the problematic one).

**Comment by michaeluno** [comment]
I cannot confirm it with the default theme. Can you provide the steps to reproduce the problem? An example theme that causes the error would be nice.

**Comment by mnajafzadeh** [comment]
Hi,

I think I found where the issue is!
In fact, this problem happens when you add a "Custom HTML" widget into your widget areas.
I already added a Custom HTML into one of my theme widget areas and I get the error. I use the AVADA theme.

Thank you.

**Comment by mnajafzadeh** [comment]
Any update?

**Comment by michaeluno** [comment]
I said I cannot reproduce the problem. I've been waiting for you to provide the steps to reproduce it.

**Comment by mnajafzadeh** [comment]
Sorry,

I already find the problem. The issue was not related to Admin Page Framework. I was my mistake in using the AdminPageFramework_Widget_Factory class.

Admin Page Framework is great!

Thank you.

**Comment by mnajafzadeh** [comment]
Hi,

Sorry to open this issue again.
I get this error when I activate the "DesignThemes Core Features Plugin" on my WordPress:

( ! ) Warning: Missing argument 1 for AdminPageFramework_Widget::__construct(), called in D:\wamp\www\wordpress4\wp-content\plugins\designthemes-core-features\page-builder\pagebuilder.php on line 141 and defined in D:\wamp\www\wordpress4\wp-content\plugins\admin-page-framework\library\apf\factory\widget\AdminPageFramework_Widget.php on line 81

I checked the AdminPageFramework_Widget.php file and I set a default value for $sWidgetTitle and it fixed the problem but still get another error that is related to the rest of this function:

( ! ) Warning: Admin Page Framework: The method is not defined: get_field_name in D:\wamp\www\wordpress4\wp-content\plugins\admin-page-framework\library\apf\factory\_common\_abstract\AdminPageFramework_Factory.php on line 152

Thank you.

**Comment by michaeluno** [comment]
Hello,

You keep not providing the steps to reproduce the error. In addition, I don't have the files of the program you mentioned. If it is a free one, you should post a link. 

> It was my mistake in using the AdminPageFramework_Widget_Factory class.
Remove the class then.

**Comment by mnajafzadeh** [comment]
Here is the plugin file:

[designthemes-core-features.zip](https://github.com/michaeluno/admin-page-framework/files/1405357/designthemes-core-features.zip)

Simply install it along with Admin Page Framework on your WordPress and enable the Admin Page Framework demo.
I do not use "AdminPageFramework_Widget_Factory class" anymore. The problem occurs when I enable the Admin Page Framework demo.

Thank you.

**Comment by michaeluno** [comment]
Does the problem only occur in WordPress v4.8? I checked their code and the problem should not be specific to v4.8 but v4.7 or earlier.

**Comment by mnajafzadeh** [comment]
Hi,

I have checked on WordPress version 4.8.2 and have problem. I have not still checked on the earlier version but, it is not important as everyone always have WordPress updated.

Thank you.

**Comment by mnajafzadeh** [comment]
Hi,

No it is not related to WordPress update. It didn't also work on WP v4.7.0 or earlier. The problem is related to a bug in Admin Page Framework or DesignThemes Core Features plugin by DesignThemes.

The error message is saying "Missing argument 1 for AdminPageFramework_Widget::__construct()"!
The DesignThemes Core Features plugin calls all the widgets created in WordPress and the widgets that are created by Admin Page Framework are having a problem that throwing an error.

Best Regards.

**Comment by michaeluno** [comment]
It is a conflict, not a bug. Admin Page Framework stores its original widget factory objects in the global `$wp_widget_factory` array and DesignThemes Core Features Plugin expects them to be of the class `WP_Widget`, which causes the error.

Specifically, in `page-builder/pagebuilder.php` (lines 139 to 141), there is
```php
			foreach($wp_widget_factory->widgets as $class => $info){
			
				$widget = new $class();
```

By changing it to the following can avoid the error.
```php
            foreach($wp_widget_factory->widgets as $class => $info){
			
                if ( ! is_subclass_of( $class, 'WP_Widget' ) ) {
                    continue;
                }
                $widget = new $class();
```
