### ISSUE TITLE
"inline_mixed" can not be used with "AdminPageFramework_Widget".

### ISSUE THREAD

**Issue by wadadanet** [michaeluno/admin-page-framework#274]
"inline_mixed" can not be used with "AdminPageFramework_Widget".
Field Types in "inline_mixed" are displayed, but can not be saved.
Also, the repeatable function does not appear to work.

## Versions

- Admin Page Framework version: 3.8.15
- WordPress version: 4.8.1
- PHP version: 5.6.28

## Code
```php
class My_Widget extends AdminPageFramework_Widget {
	public function load( $oAdminWidget ) {
		$array = array(
			"1" => 1,
			"2" => 2,
			"3" => 3,
		);
		$this->addSettingField(
			array(
				'field_id' => 'my_id',
				'type' => 'inline_mixed',
				'title' => 'title',
				'repeatable' => true,
				'sortable' => true,
				'content' => array(
					array(
						'title'         => 'select',
						'field_id'      => 'select',
						'type'          => 'select',
						'label'         => $array,
					),
				),
			)
		);
	}
	public function content( $sContent, $aArguments, $aFormData ) {
	}
}
new My_Widget(
	'my widget',
	array(
		'description'   => 'description',
	)
);
```

## Step
URL: /wp-admin/widgets.php

### 1. Select 2
![image](https://user-images.githubusercontent.com/265848/30408024-20f1d5cc-9937-11e7-843f-648f2c355b11.png)

### 3. It returns to the state where "1" is selected
![image](https://user-images.githubusercontent.com/265848/30408066-68c6c0ce-9937-11e7-8921-fb234f3b9a27.png)

**Comment by michaeluno** [comment]
I could confirm the problem. Thanks for the report.
