### ISSUE TITLE
Select2 loses feature select2 when the field is repeated

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#279]
## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [x ] The issue still exists against the latest `dev` branch.
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1.  Clean installation
2. Active demo mode
3. Go to APF demo, custom field types, Repeatable & Sortable

## Expected behavior and actual behavior

The Select2 field does not have the add button, however, CSS areeglo to be displayed.
The real problem is that by choosing a value and repeating, the duplicate field loses focus select2 and behaves like a normal select.

This problem arose me in a metabox with an inline and repetable field, every time I repeat the field, the select2 field that remains loses focus select2 and remains as a normal select.

### Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

### Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

### Versions

- Admin Page Framework version: 3.8.19
- WordPress version: 5.2.1
- PHP version: 7.2

## Isolating the problem

- [x ] This bug happens on the demo page.
- [ ] The bug happens consistently across all tested browsers.
- [x ] This bug happens with clean install (with the default theme and no plugin except the problematic one).

If you need any more information, do not hesitate to ask me.

Thank you very much for this fantastic framework and for your great work.

Best regards.

![Cap 1](https://user-images.githubusercontent.com/5380013/58411072-c66ae780-8073-11e9-998f-b6a60b3b1a72.PNG)

![Cap 2](https://user-images.githubusercontent.com/5380013/58411149-f31eff00-8073-11e9-9fc7-b0306f888bf7.PNG)

**Comment by michaeluno** [comment]
I could confirm the problem. It seems to occur with WordPress v5.0 or above. 

Thanks for the report.

**Comment by michaeluno** [comment]
It seems to occur with Select2 v4.0.6-rc.0 or above. For a workaround, you can replace the files under the `select2-custom-field-type/select2` folder (https://github.com/michaeluno/admin-page-framework/tree/3.8.19/example/library/select2-custom-field-type/select2) with the `dist` files (https://github.com/select2/select2/tree/4.0.5/dist) of [Select2 v4.0.5](https://github.com/select2/select2/archive/4.0.5.zip) for the time being.

**Comment by xarkitu** [comment]
The solution you provide removes the bug in the current version.
Thanks for the support.
Best regards.

**Comment by michaeluno** [comment]
@xarkitu v3.8.20 should fix this without any modifications. Let me know if it doesn't.
