### ISSUE TITLE
Notice: Undefined index: file in admin-page-framework\library\apf\factory\_common\utility\base_utility\AdminPageFramework_Utility.php on line 424

### ISSUE THREAD

**Issue by mupic** [michaeluno/admin-page-framework#284]
## Type of issue

- [x] Bug report.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [x] The issue still exists against the latest `dev` branch.
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1. Enable debug mod on wordpress.
2. Go to the page created with AdminPageFramework.

### Versions

- Admin Page Framework version: ^3.8
- WordPress version: 5.4.2
- PHP version: 7.4

## Direct link to the problematic code.
https://github.com/michaeluno/admin-page-framework/blob/dev/library/apf/factory/_common/utility/base_utility/AdminPageFramework_Utility.php#L423

**Comment by michaeluno** [comment]
I cannot reproduce this.

Thanks for the report anyway.
