### ISSUE TITLE
When a rich text field is edited, the formatting of the text is lost.

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#286]
## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [x] The issue still exists against the latest `dev` branch.
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1. - Open the demo menu in admin area.
2. - Edit the richtextbox field, editing title 1, paragraph, title 2 ...
3. - Save
4. - When saving, the format of the paragraphs, titles, etc., is lost.

## Expected behavior and actual behavior

When I follow those steps, I see...

Most text formats are lost.
![Captura de pantalla 2020-11-19 202930](https://user-images.githubusercontent.com/5380013/99714520-f72faf80-2aa5-11eb-9852-88b3a53c6768.jpg)
![Captura de pantalla 2020-11-19 202853](https://user-images.githubusercontent.com/5380013/99714529-fb5bcd00-2aa5-11eb-8631-7b16fd7f78a1.jpg)
![Captura de pantalla 2020-11-19 202811](https://user-images.githubusercontent.com/5380013/99714534-fd259080-2aa5-11eb-97ea-d0fa30917d8f.jpg)
![Captura de pantalla 2020-11-19 202727](https://user-images.githubusercontent.com/5380013/99714537-feef5400-2aa5-11eb-9107-56554fd99f0b.jpg)

### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

### Versions

- Admin Page Framework version: 3.8.24
- WordPress version: 5.5.3
- PHP version: 7.4 & 7.2

## Isolating the problem

- [x] This bug happens on the demo page.
- [ ] The bug happens consistently across all tested browsers.
- [ ] This bug happens with clean install (with the default theme and no plugin except the problematic one).

**Comment by michaeluno** [comment]
It seems this has started since v3.8.24.

Thanks for the report.
