### ISSUE TITLE
jQuery issue with WordPress 5.6 & PHP 8.0

### ISSUE THREAD

**Issue by jatindv** [michaeluno/admin-page-framework#287]
I have updated WordPress 5.6 & PHP 8.0 and it's throw's jQuery error & tabs is not loading please check the below screenshot.

![jqe](https://user-images.githubusercontent.com/42375000/105668961-5fff3200-5f04-11eb-985e-8b13833a5cb3.png)

**Comment by michaeluno** [comment]
Hi,

Does it occur in the demo?

**Comment by jatindv** [comment]
@michaeluno 
Hi,

Please check below video.

https://user-images.githubusercontent.com/42375000/106135554-16c21300-618e-11eb-90ec-9a2dbd3c2f80.mp4

**Comment by michaeluno** [comment]
I could reproduce the problem with PHP 8.0.

It is due to the PHP Fatal error "Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in ...AdminPageFramework_PageLoadInfo_Base.php:96."

Thanks for the report.
