### ISSUE TITLE
Character \ is removed from any field

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#289]
Hi, Michaeluno

## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [ ] The issue still exists against the latest `dev` branch.
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1. Write a text with \ in any text field, this came up when trying to write CSS in the ACE editor
2. Save
3. All the \ characters disappear, although it is not usual, in the ACE editor if it is required for some CSS classes, for example content: "\ 53 \ 53 \ 53 \ 53 \ 53"; used in WooCommerce.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

### Versions

- Admin Page Framework version: 3.8.26
- WordPress version: looked at various
- PHP version: 7.4

## Isolating the problem

- [x] This bug happens on the demo page.
- [x] The bug happens consistently across all tested browsers.
- [ ] This bug happens with clean install (with the default theme and no plugin except the problematic one).

**Comment by xarkitu** [comment]
It seems related to [this problem that I already reported](https://github.com/michaeluno/admin-page-framework/issues/286)

**Comment by michaeluno** [comment]
I could confirm the problem. It seems to have started since v3.8.24.

Thanks for the report.
