### ISSUE TITLE
Incompatibility of metabox in admin pages when moving to PHP 8

### ISSUE THREAD

**Issue by xarkitu** [michaeluno/admin-page-framework#290]
## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [x] The issue still exists against the latest `dev` branch.
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1. Look at the code I give you below, run it in PHP 7.4, the code works fine.
2. Switch to PHP 8, in my case I am testing on PHP 8.0.3
3. The metabox will stop rendering ...

## Expected behavior and actual behavior

I am looking at possible incompatibilities to move some of my clients from php 7.4 to php 8, the tests I have done so far show me a significant increase in performance and are encouraging me to make the move from PHP 7.4 to PHP 8.0.3.

When changing the version of php I realized that the metaboxes that I had created in pages without tabs disappeared, the pages that have tabs, curiously, render them well.

I have tried searching within the code but can't find the reason.

Could you look at this incompatibility with PHP 8 what is it due to?

I am not getting any php error or warning, I find it very strange ...

I attach a small plugin with an example of yours on how metaboxes work on pages:

[test-page-metabox.zip](https://github.com/michaeluno/admin-page-framework/files/6473867/test-page-metabox.zip)

### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

### Versions

- Admin Page Framework version: 3.8.27
- WordPress version: 5.7.2
- PHP version: 8.0.3

## Isolating the problem

- [x] This bug happens on the demo page.
- [x] The bug happens consistently across all tested browsers.
- [x] This bug happens with clean install (with the default theme and no plugin except the problematic one).

**Comment by michaeluno** [comment]
I could confirm this behavior. 

Thanks for the report.

**Comment by xarkitu** [comment]
Hi micheluno,

I have fixed this solution in the base plugin and in my compilation and everything seems to work correctly.

Thank you very much for your prompt attention.

Best regards..
