### ISSUE TITLE
Problems with text baseline when using inline_mixed, Chromium, Chrome, Edge only.

### ISSUE THREAD

**Issue by OllieJones** [michaeluno/admin-page-framework#293]
## Type of issue

- [x] Bug report.
- [ ] Suggestion.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate,
- [?] The issue still exists against the latest `dev` branch.
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/admin-page-framework)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue (for Bug report)

1. Look at the demo built in to your plugin: Advanced Usage / Mixed / Inline Mixed
2. Observe that the position of text for the labeling-text fields with 'content' => 'to do something else' (for example) is too low. Please see the attached screenshot
3. I cannot figure out how to correct this appearance problem with css.

## Expected behavior and actual behavior

Actual behavior in the screenshot.

Expected behavior on this page in the documentation. https://admin-page-framework.michaeluno.jp/en/v3/class-AdminPageFramework_FieldType_inline_mixed.html

## Environment

Generic WordPress install.

### Browsers

- [x] Google Chrome   fails  93
- [x] MS Edge fails  93 
- [ ] Mozilla Firefox  works ok
- [ ] Internet Explorer  works ok

### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

### Versions

- Admin Page Framework version:   3.8.33
- WordPress version: 5.8
- PHP version: 7.4.3

## Isolating the problem

- [x] This bug happens on the demo page.
- [ ] The bug happens consistently across all tested browsers.
- [x] This bug happens with clean install (with the default theme and no plugin except the problematic one).

I put red outlines into the screenshot to show the problem text. 

![image](https://user-images.githubusercontent.com/9804013/134381179-4e5dc622-9b8b-4b57-a3bd-bd8ddaed29ad.png)

**Comment by michaeluno** [comment]
I could confirm the problem. Thanks for the report.
