### ISSUE TITLE
Can't force the subpages to belong to custom main pages created without the the framework

### ISSUE THREAD

**Issue by mohamedyassin07** [michaeluno/admin-page-framework#294]
## setRootMenuPage
I used the "setRootMenuPage" to set the parent but didn't work 
- $this->setRootMenuPage('admin.php?page=main_page_slug');
- $this->setRootMenuPage('page=main_page_slug');
- $this->setRootMenuPage('admin.php?page=main_page_slug');

and no one worked with me 

## add_submenu_page
I tried to set the pages create with the framework as the main page and use the normal "add_submenu_page" WordPress method to add subpages to the main page created with the framework, but it didn't work 

any suggestions?

**Comment by michaeluno** [comment]
Try `$this->setRootMenuPageBySlug( ... )`.
