### ISSUE TITLE
Idea: Fields on User Profiles (profile.php)

### ISSUE THREAD

**Issue by patrickf0** [michaeluno/admin-page-framework#56]
Hi there, 
nice work on the taxonomy fields, looks great! ;)

I thought about the idea of having extra fields on user profiles? There is a db table for usermeta which could be used to add extra fields?

What do you think?

**Comment by michaeluno** [comment]
I'm going to start working on this one. 

What would be the best name for the factory class which will be extended?

What I can think of are:
- AdminPageFramework_User
- AdminPageFramework_UserProfile
- AdminPageFramework_UserProfileField
- AdminPageFramework_UserField

**Comment by michaeluno** [comment]
This is ready to be tested in the [3.5.0b branch](https://github.com/michaeluno/admin-page-framework/tree/3.5.0b). [Download](https://github.com/michaeluno/admin-page-framework/archive/3.5.0b.zip)

#### Example Plugin to Test
https://gist.github.com/michaeluno/5c2d4c84c84e6e17f6e0

![user_meta](https://cloud.githubusercontent.com/assets/3408158/5649335/4dc49ca6-96d8-11e4-84cf-e1802a6dd3ef.png)

Let me know if it works.
